server:
  port: 9001
spring:
  redis:
    database: 11
    port: 6379
    host: 127.0.0.1
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  application:
    name: sso-client1
sso:
  server:
    url: http://peer3:9003
  client:
    protect: /hello