server:
  port: 9001
spring:
  application:
    name: feign-consumer
eureka:
  client:
    service-url:
      #注册地址
      defaultZone: http://root:root@localhost:8082/eureka/
  #显示服务器IP加端口
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#feign常用配置
feign:
  hystrix:
    #在Feign中开启Hystrix
    enabled: true
  compression:
    request:
      #是否对请求进行GZIP压缩
      enabled: false
      #指定压缩的请求数据类型
      mime-types: text/xml,application/xml,application/json
      #超过该大小的请求会被压缩
      min-request-size: 2048
    response:
      enabled: false #是否对响应进行GZIP压缩
#该配置是让Hystrix的超时时间改为5秒
#hystrix:
#  timeoutInMilliseconds: 5000
# 配置feign日志级别
logging:
  level:
    com.jourwon.springcloud.service: debug